[package]
name = "serial_temp_logger"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.25"
egui = "0.25"
egui_plot = "0.25"
serialport = "4.2.0"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }